const quotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "Get busy living or get busy dying. - Stephen King",
  "You only live once, but if you do it right, once is enough. - Mae West",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "The only impossible journey is the one you never begin. - Tony Robbins",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
  "Life is either a daring adventure or nothing at all. - Helen Keller",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Keep your face always toward the sunshine - and shadows will fall behind you. - Walt Whitman",
  "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "The best revenge is massive success. - Frank Sinatra",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "It is never too late to be what you might have been. - George Eliot",
  "I am not a product of my circumstances. I am a product of my decisions. - Stephen Covey",
  "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do. - Mark Twain",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
  "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "You can't go back and change the beginning, but you can start where you are and change the ending. - C.S. Lewis",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Never bend your head. Always hold it high. Look the world straight in the eye. - Helen Keller",
  "What's meant to be will always find a way. - Trisha Yearwood",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The secret of getting ahead is getting started. - Mark Twain",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
  "A journey of a thousand miles begins with a single step. - Lao Tzu",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "In the middle of every difficulty lies opportunity. - Albert Einstein",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Every strike brings me closer to the next home run. - Babe Ruth",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The purpose of our lives is to be happy. - Dalai Lama",
  "Life is really simple, but we insist on making it complicated. - Confucius",
  "You miss 100% of the shots you don’t take. - Wayne Gretzky",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "You have to expect things of yourself before you can do them. - Michael Jordan",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "The best revenge is massive success. - Frank Sinatra",
  "I am not a product of my circumstances. I am a product of my decisions. - Stephen Covey",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
  "You can't go back and change the beginning, but you can start where you are and change the ending. - C.S. Lewis",
  "Life is what we make it, always has been, always will be. - Grandma Moses",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "You can't fall if you don't climb. But there's no joy in living your whole life on the ground. - Unknown",
  "You must be the change you wish to see in the world. - Mahatma Gandhi",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "Life is either a daring adventure or nothing at all. - Helen Keller",
];
export default quotes;
